version: "3.8"
services:
  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  scraper:
    build: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TARGET_URL=https://webscraper.io/test-sites/e-commerce/allinone # from: https://webscraper.io/test-sites
      - SCRAPE_INTERVAL=60
      - TOPIC_SCRAPING_EVENTS=scraping-events
    depends_on:
      - kafka

  processor:
    build: .
    command: python processor/processor.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TOPIC_SCRAPING_EVENTS=scraping-events
      - TOPIC_PRICE_UPDATES=price-updates
    depends_on:
      - kafka

  web:
    build: .
    command: python web/app.py
    ports:
      - "5050:5000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TOPIC_PRICE_UPDATES=price-updates
    depends_on:
      - kafka
